version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/hadiya/products
hooks:
  BeforeInstall:
    - location: scripts/unzip_application_bundle.sh
    - location: scripts/install_dependencies.sh
  AfterInstall:
    - location: scripts/run_database_migration.sh
  ApplicationStart:
    - location: scripts/start_application_server.sh